runtime: python311
service: app-cian-2

handlers:
  - url: /google52b7c19ec95a274e.html
    static_files: google52b7c19ec95a274e.html
    upload: google52b7c19ec95a274e.html
  
  - url: /.*
    script: auto

env_variables:
  FASTHTML_SESSION_KEY_NAME: /tmp/.sesskey
  APP_PASSWORD: "ing123"
  SECRET_KEY: "a457g68"

entrypoint: uvicorn app.main_v2:app --host 0.0.0.0 --port $PORT

instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1
