runtime: python311
service: app-cian-2

handlers:
  # Serve Google verification file
  - url: /google52b7c19ec95a274e.html
    static_files: google52b7c19ec95a274e
    upload: google52b7c19ec95a274e.html
  
  # All other requests
  - url: /.*
    script: auto

env_variables:
  FASTHTML_SESSION_KEY_NAME: /tmp/.sesskey

entrypoint: uvicorn app.main_v2:app --host 0.0.0.0 --port $PORT

instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1
